version: '3'
services: 
    #PHP Service
    #  app:
    #     build:
    #         dockerfile: ./server/php/Dockerfile
    #     image: digitalocean.com/php
    #     container_name: app
    #     restart: always
    #     tty: true
    #     environment:
    #         SERVICE_NAME: app
    #         SERVICE_TAGS: dev
    #     working_dir: /var/www
    #     volumes:
    #         - ./src:/var/www
    #         - ./server/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    #     networks:
    #         - app-network
    app:
        build:
            context: .
            dockerfile: ./server/php/Dockerfile
        image: digitalocean.com/php
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./src:/var/www
            - ./server/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
        - app-network
    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: always
        tty: true
        ports:
        - "9001:80"
        volumes:
        - ./src:/var/www
        - ./server/nginx/:/etc/nginx/conf.d/
        networks:
        - app-network
    #MySQL Service
    db:
        image: mariadb:latest
        container_name: db
        restart: always
        tty: true
        ports:
            - "13306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: roots
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./server/db/dbdata:/var/lib/mysql/
            - ./server/db/mariadb/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge